### Post WORD"
POST http://localhost:8080/v1/examples/
Content-Type: application/json

{
  "wordJapan": "母",
  "translateWord": "Mother",
  "levelN": "N5"
}

### Получить все слова из базы!"

GET http://localhost:8080/v1/examples/get-all


### Сгенерировать все файлы
POST http://localhost:8080/v1/examples/generateAll
