### Delete all
POST http://localhost:8080/v1/examples/delete

### Сгенерировать все файлы
POST http://localhost:8080/v1/examples/generateAll

###MY SQL
GET http://localhost:8080/v1/examples/get-all

### Post WORD"
POST http://localhost:8080/v1/examples/word
Content-Type: application/json

{
  "word": "雪",
  "translate": "Snow",
  "transcription": "Yuki"
}

### Get Today Words
GET http://localhost:8080/v1/examples/today

### Get /generate-today Words
GET http://localhost:8080/v1/examples/generate-today


GET http://localhost:8080/v1/examples/yesterday
