### Delete all
POST http://localhost:8080/v1/examples/deleteall

### Сгенерировать все файлы
POST http://localhost:8080/v1/examples/generateAll

###MY SQL
GET http://localhost:8080/v1/examples/get-all

### Post WORD"
POST http://localhost:8080/v1/examples/word
Content-Type: application/json

{
  "word": "1",
  "translate": "Snow2"
}

### Get Today Words
GET http://localhost:8080/v1/examples/today

### Get /generate-today Words
GET http://localhost:8080/v1/examples//generate-today
